### ISSUE TITLE
Modded containers do not always log

### ISSUE THREAD

**Issue by Binero** [fabricservertools/DeltaLogger#14]
Some containers provided by mods are not logged properly. They will either not be detected as containers, or they will be detected as containers but no transactions will be logged for them. 

# Reproduction

1. Place down a container of choice.
2. Do some transactions with said container.
3. `/dl inspect`
4. It will report either "No transactions found in container", or not even that message.

The expected behaviour is for the transactions to show up correctly as they would for Vanilla containers. 

This issue is highly reproducible on the latest version of Delta Logger, 1.0.0.

# Affected Mods

Blocks detected as containers but with transaction logging not working:
 - [Expanded Storage](https://www.curseforge.com/minecraft/mc-mods/expanded-storage-fabric) 5.6.32: chests (barrels work correctly)
 - [Adorn](https://modrinth.com/mod/adorn) 1.13.0: drawers
 - [Kibe](https://www.curseforge.com/minecraft/mc-mods/kibe) 1.16.3 beta 3: Entangled Chest
 - [Crafting Stations](https://www.curseforge.com/minecraft/mc-mods/improved-stations) 2.0.3: crafting station

Blocks not detected as containers:
 - [Tech Reborn](https://www.curseforge.com/minecraft/mc-mods/techreborn) 3.8.0: electric furnace
 - [Modern Industrialisation](https://modrinth.com/mod/modern-industrialization) 0.3.12: steel boiler
 - [Industrial Revolution](https://www.curseforge.com/minecraft/mc-mods/industrial-revolution) 1.8.10 beta: Mining Rig Computer

Blocks correctly logging transactions:
 - [Blockus](https://www.curseforge.com/minecraft/mc-mods/blockus) 2.0.2: barrels
 
The lists are of course not exhaustive. 

# Possible Solutions

In general it would be nice if "usages" of blocks were also tracked, in cases where transaction logging would be impossible. Block Logger also has trouble detecting transactions in these containers, but because it shows the block has been used, so server administrators aren't completely left in the dark!

**Comment by yitzy299** [comment]
So, as we've discussed on the discord, this relates the mods that use custom ScreenHandlers to provide their containers. This causes problems for DeltaLogger, which relies on mixing into the vanilla ScreenHandler. This could possibly be fixed with a mixin plugin, triggering a compatibility mixin which mixes into the mod's custom ScreenHandler.

**Comment by Binero** [comment]
I believe this was closed prematurely. I tested on the merged branch, but I saw no difference in which transactions were logged and which ones were not.
