### ISSUE TITLE
Soft overriding AbstractBlock.AbstractBlockState#onUse

### ISSUE THREAD

**Issue by GabrielOlvH** [fabricservertools/DeltaLogger#16]
**Describe the bug**
Your [mixin](https://github.com/fabricservertools/DeltaLogger/blob/master/src/main/java/com/github/fabricservertools/deltalogger/mixins/BlockInteractionMixin.java) is a soft override that doesn't let any other mixins in that method run after it.

**To Reproduce**
It can be noticed with Carrier installed, you are not able to pickup anything with DeltaLogger.

**Expected behavior**
Don't override the method.

**Screenshots**

**Specs:**
 - Version DeltaLogger v1.0.0-1.16.5

You should just ``return`` instead of setting the return value [here](https://github.com/fabricservertools/DeltaLogger/blob/master/src/main/java/com/github/fabricservertools/deltalogger/mixins/BlockInteractionMixin.java#L52-L60). Also, tiny nitpick, that's also duplicated code.

**Comment by GabrielOlvH** [comment]
That looks better, thank you!

**Comment by PotatoPresident** [comment]
There is no reason for this to be a mixin. I'll switch to to use the FAPI event sometime this weekend

**Comment by yitzy299** [comment]
> There is no reason for this to be a mixin. I'll switch to to use the FAPI event sometime this weekend

Will close once this is done, thanks for reporting

**Comment by yitzy299** [comment]
I can switch this over to FAPI later, but the issue has now been fixed
