### ISSUE TITLE
[feature req] add luckperms support

### ISSUE THREAD

**Issue by andrewzah** [fabricservertools/DeltaLogger#20]
Now that [LuckPerms supports Fabric](https://github.com/lucko/LuckPerms/pull/2029) it would be nice to have granular permissions for commands. Particularly `/dl resetpass` as I want to limit that to certain groups.

**Comment by yitzy299** [comment]
I'm not gonna work on this until the is an official fabric permissions API. You can use https://github.com/gegy/player-roles if you need a luckperms alternative that works

**Comment by yitzy299** [comment]
Just wanted to add that resetpass should be locked to ops, if you don't trust someone with webui view perms then giving them op likely isn't a great idea

**Comment by yitzy299** [comment]
Added in latest commit
