### ISSUE TITLE
missing library bug?

### ISSUE THREAD

**Issue by TheNukeLore** [fabricservertools/DeltaLogger#24]
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 2/27/21 3:22 PM
Description: Exception in server tick loop

org.jdbi.v3.core.ConnectionException: java.sql.SQLException: No suitable driver found for jdbc:sqlite:/data/starter_world/deltalogger.sqlite
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.5)
	at org.jdbi.v3.core.Jdbi.open(Jdbi.java:318)
	at org.jdbi.v3.core.Jdbi.withHandle(Jdbi.java:339)
	at com.github.fabricservertools.deltalogger.DatabaseManager.runScript(DatabaseManager.java:187)
	at com.github.fabricservertools.deltalogger.DatabaseManager.checkValidSchema(DatabaseManager.java:225)
	at com.github.fabricservertools.deltalogger.DatabaseManager.connect(DatabaseManager.java:97)
	at com.github.fabricservertools.deltalogger.DatabaseManager.<init>(DatabaseManager.java:72)
	at com.github.fabricservertools.deltalogger.DatabaseManager.create(DatabaseManager.java:79)
	at com.github.fabricservertools.deltalogger.ModInit.onServerSetup(ModInit.java:53)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$0(ServerLifecycleEvents.java:37)
	at net.minecraft.server.MinecraftServer.handler$zll000$beforeSetupServer(MinecraftServer:2238)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:645)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: No suitable driver found for jdbc:sqlite:/data/starter_world/deltalogger.sqlite
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at org.jdbi.v3.core.Jdbi.lambda$create$0(Jdbi.java:114)
	at org.jdbi.v3.core.Jdbi.open(Jdbi.java:303)
	... 12 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 4.4.234-1.el7.elrepo.x86_64
	Java Version: 1.8.0_275, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 420521360 bytes (401 MB) / 1006632960 bytes (960 MB) up to 1006632960 bytes (960 MB)
	CPUs: 8
	JVM Flags: 26 total; -XX:+UnlockExperimentalVMOptions -Xmx960M -Xms960M -XX:MaxMetaspaceSize=256m -XX:CompressedClassSpaceSize=64m -XX:+UseCompressedOops -XX:+UseCompressedClassPointers -XX:+UseLargePagesInMetaspace -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=200 -XX:+DisableExplicitGC -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:-OmitStackTraceInFastThrow -XX:+AlwaysPreTouch -XX:MaxTenuringThreshold=1 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:SurvivorRatio=32 -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:InitiatingHeapOccupancyPercent=15
	Suspected Mods: jdbi3-core (org_jdbi_jdbi3-core), Fabric Lifecycle Events (v1) (fabric-lifecycle-events-v1), DeltaLogger (deltalogger)
	Fabric Mods: 
		adventure-platform-fabric: adventure-platform-fabric 4.0.0-SNAPSHOT
		autoconfig1u: Auto Config v1 Updated 3.3.1
		cardinal-components-base: Cardinal Components API (base) 2.7.1
		cardinal-components-entity: Cardinal Components API (entities) 2.7.1
		carpet: Carpet Mod in Fabric 1.4.27
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.8.3
		com_github_ben-manes_caffeine_caffeine: caffeine 2.8.0
		com_graphql-java_graphql-java: graphql-java 16.1
		com_graphql-java_java-dataloader: java-dataloader 2.2.3
		com_zaxxer_hikaricp: HikariCP 3.4.2
		deltalogger: DeltaLogger 1.0.0
		dynmap: Dynmap 3.1-beta7
		extraorigins: Extra Origins 1.16.5-1
		fabric: Fabric API 0.30.0+1.16
		fabric-api-base: Fabric API Base 0.2.0+daa38b3d7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.0.10+ca58154a7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.10+ca58154a7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.2+ca58154a7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.4.21+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.3+ca58154a7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.1+ca58154a7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.1
		fallflyinglib: FallFlyingLib 1.1.0
		fiblib: FibLib 1.0.0
		invview: InvView 1.4.0-1.16.4+
		io_leangen_geantyref_geantyref: geantyref 1.3.7
		java: OpenJDK 64-Bit Server VM 8
		lithium: Lithium 0.6.3
		minecraft: Minecraft 1.16.5
		mysql_mysql-connector-java: mysql-connector-java 8.0.19
		net_kyori_adventure-api: adventure-api 4.4.0
		net_kyori_adventure-key: adventure-key 4.4.0
		net_kyori_adventure-platform-api: adventure-platform-api 4.0.0-SNAPSHOT
		net_kyori_adventure-text-feature-pagination: adventure-text-feature-pagination 4.0.0-SNAPSHOT
		net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.1.0-SNAPSHOT
		net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.4.0
		net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.4.0
		net_kyori_examination-api: examination-api 1.0.0
		net_kyori_examination-string: examination-string 1.0.0
		notenoughcrashes: Not Enough Crashes 3.1.7
		org_antlr_antlr4-runtime: antlr4-runtime 4.8
		org_jdbi_jdbi3-core: jdbi3-core 3.12.2
		org_jdbi_jdbi3-sqlite: jdbi3-sqlite 3.12.2
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_reactivestreams_reactive-streams: reactive-streams 1.0.3
		org_slf4j_slf4j-api: slf4j-api 1.8.0-beta4
		org_xerial_sqlite-jdbc: sqlite-jdbc 3.32.3.2
		origins: Origins 0.4.7
		packet_tweaker: Packet Tweaker 0.1.1
		pehkui: Pehkui 1.7.1+21w03a
		phosphor: Phosphor 0.7.0+build.10
		placeholder-api: Fabric Placeholder API 0.2.1
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		sax: Simple Anti X-Ray 1.0.0
		server_translations_api: Server Translations API 1.4.0
		statement: Statement 4.0.0+1.16.2
		styledplayerlist: Styled Player List 1.2.0
		towelette: Towelette 4.1.6+1.16.2
		unpatchzerotickfarm: Un-Patch Zero Tick Farms v1.0.7-1.16.3
	Data Packs: vanilla (incompatible), Fabric Mods, file/VanillaTweaks_c423876.zip, file/afk display v1.1.0.zip, file/armor statues v2.8.1.zip, file/cauldron concrete v2.0.3.zip, file/custom nether portals v2.3.2.zip, file/double shulker shells v1.3.0.zip, file/durability ping v1.1.0.zip, file/gem villagers v4.3.2.zip, file/more mob heads v2.8.2.zip, file/multiplayer sleep v2.5.2.zip, file/player head drops v1.1.0.zip, file/silence mobs v1.1.0.zip, file/track raw statistics v1.4.0.zip, file/track statistics v1.1.0.zip, file/treasure gems v1.2.1.zip, file/wandering trades v1.4.0.zip, file/newvanilla-1-4-1-cegress (1).zip, file/timber v2.1.1.zip, file/Merling_Extra(3).zip, file/craftable-chainmail-datapack.zip (incompatible), file/Piglin_Turtle_Drop(2).zip
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
**Screenshots**

**Specs:**
 - Version [eg. DeltaLogger v1.0.0]
 - OS: [e.g. Linux]
 - Java version [e.g. 11]

**Logs**
Please attach a link to a paste site with your `latest.log`

**Comment by konsolas** [comment]
More information in #25
