### ISSUE TITLE
Conflict with Dynmap [megathread]

### ISSUE THREAD

**Issue by yitzy299** [fabricservertools/DeltaLogger#25]
When using Dynmap, DeltaLogger crashes with a driver not found exception. This has to do with Dynmap also bundling SQLite

**Comment by SuperTails** [comment]
Crash Report:
https://paste.rs/tyS
Log file:
https://paste.rs/XYU
(Deltalogger 1.0.0, Dynmap 3.1-beta7, Fabric API 0.31.0)

**Comment by yitzy299** [comment]
Spoken to the Dynmap dev, we've confirmed the issue as both bundling the database connectors: I think we'll have a solution soon

**Comment by yitzy299** [comment]
Removing the milestone as the dynmap dev says he's gonna try a fix, thanks for reporting

**Comment by yitzy299** [comment]
So, Dynmap 3.1-beta6 does work, please use that for now

**Comment by yitzy299** [comment]
Not much can be done from our end, and there's a workaround

**Comment by evanbones** [comment]
Dynmap 3.1-beta6 works, but the full release version doesn't
