### ISSUE TITLE
Server crashes because "attacker is null" in certain entity death scenarios

### ISSUE THREAD

**Issue by Justsnoopy30** [fabricservertools/DeltaLogger#27]
**Describe the bug**
DeltaLogger causes a server crash because "attacker is null" in certain entity death scenarios such as when a named, summoned as part of a structure Hoglin is killed by lava.

**To Reproduce**
1. Install Incendium datapack (https://www.planetminecraft.com/data-pack/incendium-nether-expansion/)
2. Generate a castle with `give @s jigsaw{BlockEntityTag:{joint:"rollable",name:"starmute:floor",pool:"starmute:castle/floor_l1",final_state:"minecraft:basalt",id:"minecraft:jigsaw",target:"starmute:floor"},display:{Lore:['"(+NBT)"']}}`, then place it oriented to the side, set levels to 7 and hit generate.
3. Pour lava on a hoglin

**Expected behavior**
The hoglin should die and the server should not crash

**Screenshots**
![image](https://user-images.githubusercontent.com/33374736/109409695-7e6ca900-795a-11eb-9cb1-f0cb1042ee3c.png)

**Specs:**
 - Version: DeltaLogger v1.0.0 (tested with latest github actions build too)
 - OS: Linux
 - Java Version: 15

**Logs**
[crash-2021-02-28_00.12.22-server.txt](https://github.com/fabricservertools/DeltaLogger/files/6056322/crash-2021-02-28_00.12.22-server.txt)
[crash-2021-02-28_00.14.48-server.txt](https://github.com/fabricservertools/DeltaLogger/files/6056323/crash-2021-02-28_00.14.48-server.txt)

**Comment by yitzy299** [comment]
I'll fix that later, thanks for reporting
