### ISSUE TITLE
Javalin?

### ISSUE THREAD

**Issue by srnyx** [fabricservertools/DeltaLogger#35]
**Describe the bug**
Strange error about Javalin. There is one in the middle of startup and one in the end

**To Reproduce**
Use the mod

**Expected behavior**
No error

**Specs:**
 - Version: 1.1.0
 - OS: I think Linux
 - Java version: I'm not sure, probably the most common one

**Logs**
I don't think the full log is necessary for this: https://pastebin.com/ziUtruuU

**Comment by yitzy299** [comment]
Can be safely ignored
