### ISSUE TITLE
crash due to BLOB/TEXT column 'state' used in key 

### ISSUE THREAD

**Issue by Altirix** [fabricservertools/DeltaLogger#38]
**Describe the bug**
Crash using mysql [13:35:41] [Server thread/ERROR]: Encountered an unexpected exception
org.jdbi.v3.core.statement.UnableToExecuteStatementException: java.sql.BatchUpdateException: BLOB/TEXT column 'state' used in key 

**To Reproduce**
Start server with MYSQL and deltalogger

**Expected behavior**
no crash

**Specs:**
 - Version DeltaLogger v1.1.0
 - OS: Ubuntu
 - Java version 8

**Logs**
https://pastebin.com/wTj2xP69

**Comment by yitzy299** [comment]
I’m aware, the advise remains to not use MySQL unless you’re making a custom webui

**Comment by Altirix** [comment]
thank you, sorry must have missed the issue i duplicated.
