### ISSUE TITLE
[Enhancement] Add ability to rollback entities

### ISSUE THREAD

**Issue by EvilSquirrelGuy** [fabricservertools/DeltaLogger#40]
**Is your feature request related to a problem? Please describe.**
To be able to roll back entities, for example villagers or sheep, that were killed by a griefer

**Describe the solution you'd like**
The rollback command to be able to roll back entities as well as blocks and containers

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by yitzy299** [comment]
Made these simple as of the latest commit, will take a look soon

**Comment by yitzy299** [comment]
I have some changes I’d like to make to the entity migration script, which is just storing NBT rather than things like name

**Comment by yitzy299** [comment]
<:tiny_potato:552977803633623040>
