### ISSUE TITLE
Randomly getting kicked when putting items in containers

### ISSUE THREAD

**Issue by BootSwitch** [fabricservertools/DeltaLogger#41]
**Describe the bug**
Ever since I have installed DeltaLogger, me and my friends would randomly get kicked when shift clicking items into containers like kettles and furnaces. 

`[10:31:51] [Server thread/INFO]: (username) lost connection: Internal Exception: java.lang.IndexOutOfBoundsException: Index: 37, Size: 37`

Instead of 37, it can also be 41, 39, 37, etc...

**To Reproduce**
1. Install my mods (I guess?)
2. Shift click an item into a furnace and it will kick you

**Expected behavior**
I expected to not be kicked when shift clicking something into a furnace.

**Screenshots**
This person has the same issue.

![image](https://user-images.githubusercontent.com/65787561/110634801-4824fa00-81a2-11eb-8801-db90293f5479.png)

**Specs:**
 - Version DeltaLogger 1.1.1
 - OS: Linux (I use a server host so I don't know too much)
 - Java version: 8

**Logs**
https://bin.bloom.host/tegoyiqoka
https://bin.bloom.host/ogegudodud

**Comment by yitzy299** [comment]
If you can reproduce without cardboard, please reopen the issue

**Comment by Setadokalo** [comment]
I also get this error, with *these* mods:
```BlueMap-1.3.1-fabric-1.16.4.jar            FabricProxy-Lite-1.1.0.jar            infinity-water-bucket-1.0.3.2-compat-mc1.16.4-fabric.jar  spark-fabric.jar
chatplus-1.0.1.jar                         fabrictailor_fabric-1.4.0-1.16.4.jar  infinityfix-1.1.0.jar                                     styledplayerlist-1.1.2.jar
commandaliases-0.4.1.jar                   fairenchanting-1.2.0.jar              ladderwarp-1.1.0+1.16.x.jar                               tdnf-mc116-2.1.128.jar
config-2-4.8.3.jar                         faster-minecarts-1.1.2.jar            lapisreserve-1.0.6.jar                                    textile_backup-2.1.0-prev-1.16.4.jar
deltalogger-1.16.5-1.1.0.jar               flan-1.16.2-1.2.2.jar                 leaf-decay-1.2.0-1.16.1.jar                               TomsServerTools-0.1.3.local.jar
disguiselib-0.1.0.jar                      GiantAI-1.0.4.jar                     lithium-fabric-mc1.16.5-0.6.3.jar                         vanilladeathchest-1.16.3-1.11.0.7-fabric.jar
fabric-api-0.30.3+1.16.jar                 Harvest-fabric-1.16.1-1.2.12-26.jar   phosphor-fabric-mc1.16.3-0.7.0+build.10.jar               visualoverhaul-2.0.1.jar
fabric-console-1.0.3+1.16.3.jar            hypnos-0.1.1.jar                      repairable-tridents-1.0.0.jar                             wanderingcollector-1.0.0+mc1.16.5.jar
```

Narrowing that down to just mods shared by all 3 of us, that leaves only 3 mods in common: Deltalogger, Lithium, and Phosphor. I think we can relatively safely say it's not a problem with Lithium or Phosphor.

**Comment by yitzy299** [comment]
I'll have a look in a moment

**Comment by yitzy299** [comment]
I cannot reproduce, if this is a mod compat issue then please ask the devs. I also can see your host is using java 7, below the minimum needed to run both MC and DeltaLogger. If you can reproduce this with only DeltaLogger, please tell me

**Comment by yitzy299** [comment]
I'd love some help, perhaps even videos of this issue as I really can't reproduce

**Comment by yitzy299** [comment]
@konsolas any ideas?

**Comment by konsolas** [comment]
I'll have another look

**Comment by yitzy299** [comment]
@BootSwitch @Setadokalo Can you check if the latest actions jar fixes it?

**Comment by BootSwitch** [comment]
I'll have a look, thank you.

**Comment by BootSwitch** [comment]
When being kicked as well, the items they shift clicked into a furnace also duplicate.

**Comment by BootSwitch** [comment]
I will comment back after a day, to test if it happens again.

**Comment by konsolas** [comment]
![image](https://user-images.githubusercontent.com/9408210/111030377-c929fe80-83f9-11eb-83af-8cce352d86a5.png)

**Comment by yitzy299** [comment]
Will remove this label if anything comes up, otherwise I'll close if we don't get anything more soon

**Comment by BootSwitch** [comment]
Everything is fixed (for me), well done on the fix and thank you! 👍

**Comment by yitzy299** [comment]
Looks good, let me know if it comes back again
