### ISSUE TITLE
[Feature] Add co-ordinates to transactions

### ISSUE THREAD

**Issue by BootSwitch** [fabricservertools/DeltaLogger#43]
**Describe the solution you'd like**
If someone takes something out of a chest, it should say the co-ordinates of the chest that the items were taken out of.

**Describe alternatives you've considered**
Possibly also make it show the username of the person who actually placed the chest down. This could be used to identify people's chests.

**Comment by yitzy299** [comment]
I'll close it, was fixed in the latest commit
