### ISSUE TITLE
Licensing Clarifications

### ISSUE THREAD

**Issue by Rubydesic** [fabricservertools/DeltaLogger#47]
This project doesn't use a standard OSI approved license.

- Does my server have to be AGPL if this mod is included?
- Does my modpack have to be AGPL if this mod is included?
- Does my mod have to be AGPL if it implements compatibility with this mod?

**Comment by yitzy299** [comment]
Please read the license and linking clause, it is explained clearly

**Comment by Rubydesic** [comment]
It is not explained clearly to me. Will you answer with yes/no?

**Comment by TheEpicBlock** [comment]
The AGPL is a standard OSI approved license. Besides that, the project clearly gives you additional permission to link with the project without the requirements of the AGPL. So no, you don't need to be AGPL to link to the project.
