### ISSUE TITLE
Add blockstate/data and NBT logging

### ISSUE THREAD

**Issue by EvilSquirrelGuy** [fabricservertools/DeltaLogger#55]
**Is your feature request related to a problem? Please describe.**
When rolling back areas that are griefed, block data and NBT gets reset to the default, such as stuff stored in chests, stair orientation, etc. After rolling back areas, all chests are empty and slabs are reset.

**Describe the solution you'd like**
For blockstates and NBT data to be properly logged so it can be rolled back.

**Describe alternatives you've considered**
Using a backup script and copying the affected region files manually from the backup.

**Additional context**
N/A

**Comment by yitzy299** [comment]
It's already logged: there's a state column in the placements table. Not sure about item NBT data

**Comment by yitzy299** [comment]
This has now been done for blocks, I'll take a look at items now
