### ISSUE TITLE
Suggestion: more Logs and rollback 

### ISSUE THREAD

**Issue by emielderckx** [fabricservertools/DeltaLogger#63]
I was founding so much things not logged that I will puth everything in 1 issue for now :0 <3

1. Make it possible to log & rollback creeper/ghasts explosions. maybe make it possible to see what stupid guy made the creeper angry.

2. Log and rollback vine growth

3. Water can break a lot of things (plants etc) it would be nice if that could be logged and rollbacked

4. Falling sand/gravel/concrete can not be rollbacked/logged

5. Log/rollback natural block breakage (ex: if a sign pops off a dirt block that was broken)

This is everything I tested but there is prob more missing :) 
This would be a good list to follow, it contains the most things you can even log in minecraft: https://mcpaste.io/7fcea3c336cac6d8

**Comment by yitzy299** [comment]
Creepers and ghosts are already logged. Plant growth is out of scope as it’s a natural interaction. Blocks broken by water would be an issue with FAPI and not us, as we use the FAPI block break event. I’ll take a look at consequential breaks but they would hard to log
